name: Deploy using rsync
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install rsync
        run: sudo apt install rsync -y
      - name: Build source code
        run: |
          npm ci
          npm run build
      - name: Copy build
        run: |
          eval $(ssh-agent -s)
          echo "$DEPLOYMENT_SSH_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p $DEPLOYMENT_SSH_PORT $DEPLOYMENT_SSH_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          rsync -az -e "ssh -p $DEPLOYMENT_SSH_PORT" ./build/ $DEPLOYMENT_SSH_USER@$DEPLOYMENT_SSH_HOST:$DEPLOYMENT_PROJECT_PATH
          ssh $DEPLOYMENT_SSH_USER@$DEPLOYMENT_SSH_HOST -p $DEPLOYMENT_SSH_PORT 'cd ~/$DEPLOYMENT_PROJECT_PATH && npm ci --ignore-scripts && node ace migration:run && pm2 restart $DEPLOYMENT_PM2_NAME -a'
        env:
          DEPLOYMENT_SSH_KEY: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          DEPLOYMENT_SSH_HOST: ${{ secrets.DEPLOYMENT_SSH_HOST }}
          DEPLOYMENT_SSH_PORT: ${{ secrets.DEPLOYMENT_SSH_PORT }}
          DEPLOYMENT_SSH_USER: ${{ secrets.DEPLOYMENT_SSH_USER }}
          DEPLOYMENT_PROJECT_PATH: ${{ secrets.DEPLOYMENT_PROJECT_PATH }}
          DEPLOYMENT_PM2_NAME: ${{ secrets.DEPLOYMENT_PM2_NAME }}