name: Deploy using rsync
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install rsync
        run: sudo apt install rsync -y
      - name: Build source code
        run: |
          npm ci
          npm run build
      - name: Copy build
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p $PORT $HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          rsync -az -e "ssh -p $PORT" ./build/ $USER@$HOST:~/Projects/creator_api
          ssh $USER@$HOST -p $PORT 'cd ~/Projects/creator_api && npm ci --ignore-scripts && node ace migration:run && pm2 restart creator_api -a'
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USER: ${{ secrets.USER }}
